### ISSUE TITLE
Add proxy-component to release notes

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok-workflow-rest-services#149]
Since https://github.com/adaptris/interlok-workflow-rest-services/pull/148 introduces a new optional component.
This needs an icon + releasenotes.

**Comment by sebastien-belin-adp** [comment]
Closing this issue as 4.3 has been released and that was added to the release note https://interlok.adaptris.net/interlok-docs/#/pages/overview/changelog?id=version-430
